### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by ivirshup** [kaizhang/anndata-rs#1]
First off looks cool! Looking forward to trying it out.

Not super familiar with rust development, so took me a bit to figure out. Are these the steps to install?

```
# From root of repo
$ cd python
$ mkdir anndata_rs
$ pip install -e .
```

**Comment by kaizhang** [comment]
I haven't released this as an independent package. This is mainly for internal use right now and It is now bundled with the SnapATAC2 package which can be easily installed by: `pip install snapatac2`.

Then you have access to anndata_rs related functions below:

- snapatac2.read
- snapatac2.read_mtx
- snapatac2.read_dataset
- snapatac2.create_dataset

I can provide some documentation if you are interested in testing out.

**Comment by ivirshup** [comment]
I'd definitely be interested in testing this out!

I'd also like the opportunity to chat about this implementation, and what your plans are for it. There's some interesting stuff going on in the ecosystem – like the [matrix-api](https://github.com/single-cell-data/matrix-api) being organized by the cellxgene devs and the use of anndata in ome-ngff for spatial data ([ome-ngff-tables-prototype](https://github.com/kevinyamauchi/ome-ngff-tables-prototype)). 

Some things we could talk about:

* Scope of plans for this library
* How do we maintain compatibility between this and python anndata
* Use of arrow, thoughts about tensor support
* Are there some useful places we can consolidate effort?

Would you be up to chat sometime about this?

**Comment by kaizhang** [comment]
I'm happy to chat about these with you! My time is more flexible at weekends if that's work for you. Otherwise, I'm generally available from 3PM to 11PM PDT.

**Comment by ivirshup** [comment]
Oof, those times are kinda rough for CET. I'm thinking we might need a doodle.

Would you be up for joining the scverse zulip (https://scverse.zulipchat.com) to plan? Otherwise I can email.

**Comment by kaizhang** [comment]
Documentation added: http://kzhang.org/anndata-rs/api.html
