### ISSUE TITLE
[Help] read h5ad in pure rust fail

### ISSUE THREAD

**Issue by zqfang** [kaizhang/anndata-rs#4]
Hi Kai,

Thank you for your excellent work. I have trouble in reading the h5ad file into pure rust code. Would you help me give me some insight?

The code I've used is below. I am wondering whether I am do it right or not
```rust
fn read_h5ad(filename: PathBuf) -> AnnData<H5> {
    let pbuf = H5::open::<PathBuf>(filename);
    let adata = AnnData::<H5>::open(pbuf.unwrap()).map(|adata| adata.into()).unwrap();
    return adata;

}
fn main() {
    // let _fh55 = File::open("test.h5ad").expect("read h5ad in");
    let fh5 = Path::new("./test.h5ad");
    let adata = read_h5ad(fh5.to_path_buf());

    println!("{:?}", data);
}




// fn read_h5ad(filename: PathBuf, mode: &str, backend: Option<&str>) -> AnnData<H5>{
//     match backend.unwrap_or(H5::NAME) {
//         H5::NAME => {
//             let file = match mode {
//                 "r" => H5::open(filename)?,
//                 "r+" => H5::open_rw(filename)?,
//                 _ => bail!("Unknown mode: {}", mode),
//             };
//         anndata::AnnData::<H5>::open(file).map(|adata| adata.into())

//     }
// }


```

**Comment by kaizhang** [comment]
I didn't try to compile it. But something similar to this should work.

```
fn read_h5ad(filename: PathBuf) -> AnnData<H5> {
    let pbuf = H5::open::<PathBuf>(filename);
    AnnData::<H5>::open(pbuf.unwrap()).unwrap()
}
```

**Comment by zqfang** [comment]
I've tried the same code. but do not work

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Cannot read shape information from type 'Mapping'

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/backtrace.rs:332:13
   3: std::backtrace::Backtrace::capture
             at /rustc/07c993eba8b76eae497e98433ae075b00f01be10/library/std/src/backtrace.rs:298:9
   4: anyhow::error::<impl anyhow::Error>::msg
             at /Users/zqfang/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.69/src/error.rs:83:36
   5: <anndata::data::array::ArrayData as anndata::data::data_traits::ReadArrayData>::get_shape
             at /Users/zqfang/Github/SCLens/anndata/src/data/array.rs:196:19
   6: <anndata::container::base::Slot<anndata::container::base::InnerArrayElem<B,anndata::data::array::ArrayData>> as core::convert::TryFrom<anndata::backend::DataContainer<B>>>::try_from
             at /Users/zqfang/Github/SCLens/anndata/src/container/base.rs:635:20
   7: anndata::anndata::AnnData<B>::open
             at /Users/zqfang/Github/SCLens/anndata/src/anndata.rs:109:21
   8: sclens::read_h5ad
             at ./src/main.rs:36:17
   9: sclens::main
             at ./src/main.rs:64:17
```

**Comment by kaizhang** [comment]
Yes, you can try this anndata: https://data.mendeley.com/api/datasets/dr2z4jbcx3/draft/files/d90adfd1-b4b8-4dcd-8704-9ab19f104116?a=758c37e5-4832-4c91-af89-9a1a83a051b3

**Comment by zqfang** [comment]
Hi Kai, the toy h5ad Work ! 

> Yes, you can try this anndata: https://data.mendeley.com/api/datasets/dr2z4jbcx3/draft/files/d90adfd1-b4b8-4dcd-8704-9ab19f104116?a=758c37e5-4832-4c91-af89-9a1a83a051b3

My test.h5ad is converted by `MuDataSeurat::Write_H5AD()`. 

So the issue is the `anndata-rs` is not fully compatible with my converted test.h5ad.

Need to find out what's missing then

**Comment by kaizhang** [comment]
Please feel free to send me the h5ad file that doesn't work and I will investigate the issue when I have time.

**Comment by zqfang** [comment]
Thank you so much Kai. Please find the file here
[test.zip](https://github.com/kaizhang/anndata-rs/files/10935762/test.zip)


BTW, Do you have plans or Is it possible to implement `.layers` ? It's important to layers when you want to save raw counts, lognorm counts, scaled data in one the same object.

**Comment by kaizhang** [comment]
Layers should be straightforward to implement. I will work on that once I have some free time.

**Comment by zqfang** [comment]
That's awesome ! I'm looking forward to it. 

Let me know if I can help. However, my rust skills are limited, and need guidelines.

One more question, do you think you'll plan to add MuData implementation?  It would be wonderful to support multi-omics objects in rust.

**Comment by kaizhang** [comment]
> That's awesome ! I'm looking forward to it.
> 
> Let me know if I can help. However, my rust skills are limited, and need guidelines.
> 
> One more question, do you think you'll plan to add MuData implementation? It would be wonderful to support multi-omics objects in rust.

Layers are now implemented. Something similar to MuData is helpful, but I need to think about the design first.
