### ISSUE TITLE
Extrac gene expression time

### ISSUE THREAD

**Issue by Liripo** [kaizhang/anndata-rs#9]
I would like to ask, I have h5ad with 300,000 cells, and it takes 12 seconds to extract a single gene. Is there any way I can optimize this? I don't want to load the data into memory. I hope to control the time to 3~4s.

```py
import snapatac2 as snap
adata = snap.read("my.h5ad")
adata.X[:,1]
```

**Comment by kaizhang** [comment]
The `.X` is stored as CSR matrix by default, which is not optimized for column data retrieval. Changing the `.X` into CSC matrix may help in this case.

**Comment by Liripo** [comment]
Thank you for your reminder
